Update astro.yml
Signed-off-by: AU_gdev_19 <64915515+Dargon789@users.noreply.github.com>

diff --git a/.github/workflows/astro.yml b/.github/workflows/astro.yml
--- a/.github/workflows/astro.yml
+++ b/.github/workflows/astro.yml
@@ -25,8 +25,7 @@ concurrency:
   cancel-in-progress: false
 
 env:
-  BUILD_PATH: "." # default value when not using subfolders
-  # BUILD_PATH: subfolder
+  BUILD_PATH: subfolder # default value when not using subfolders
 
 jobs:
   build:
@@ -36,24 +35,23 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager. Please ensure 'yarn.lock' or 'package.json' exists in the repository."
-            exit 1
-          fi
+    run: |
+      if [ -f "${{ github.workspace }}/${{ env.BUILD_PATH }}/yarn.lock" ]; then
+        echo "manager=yarn" >> $GITHUB_OUTPUT
+        echo "command=install" >> $GITHUB_OUTPUT
+        echo "runner=yarn" >> $GITHUB_OUTPUT
+        echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
+        exit 0
+      elif [ -f "${{ github.workspace }}/${{ env.BUILD_PATH }}/package.json" ]; then
+        echo "manager=npm" >> $GITHUB_OUTPUT
+        echo "command=ci" >> $GITHUB_OUTPUT
+        echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+        echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
+        exit 0
+      else
+        echo "Unable to determine package manager. Please ensure 'yarn.lock' or 'package.json' exists in the ${BUILD_PATH} folder."
+        exit 1
+      fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
@@ -77,13 +75,12 @@ jobs:
         with:
           path: ${{ env.BUILD_PATH }}/dist
 
-  deploy:
+    deploy:
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     needs: build
-    runs-on: ubuntu-latest
-    name: Deploy
+runs-on: ubuntu-latest
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
