Update .github/workflows/makefile.yml
Co-authored-by: sourcery-ai[bot] <58596630+sourcery-ai[bot]@users.noreply.github.com>
Signed-off-by: AU_gdev_19 <64915515+Dargon789@users.noreply.github.com>

diff --git a/.github/workflows/makefile.yml b/.github/workflows/makefile.yml
--- a/.github/workflows/makefile.yml
+++ b/.github/workflows/makefile.yml
@@ -21,9 +21,9 @@ jobs:
     - name: Verify configure.ac existence
       run: |
          if [ ! -f configure.ac ]; then
-      if: Missing configure.ac file. Please add it to the repository."
-          exit 1
-          fi
+           echo "Missing configure.ac file. Please add it to the repository."
+           exit 1
+         fi
 
     - name: Generate configure script
       run: autoreconf --install
